#!/usr/bin/env python

import requests, json, random
import facebook

# Constants - to move to config file.
app_id = '<<YOUR-APP_ID>>'
app_key = '<<YOUR-APP_KEY>>'
access_token = '<<YOUR-ACCESS_TOKEN>>'

message="hmm..."

# Post to Facebook
try:
    graph = facebook.GraphAPI(access_token=access_token)
    graph.put_wall_post(message)
except Exception as e:
    print 'Exception: ' + str(e)
    pass
